# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b382b883a4231a61e6f64ca491563bae31a04807fcdbaae582851cbf6119756a2cef0c560db2242abea75328ad5e305054ba000c5c1ef61a232a507f4ff59774

test:
  secret_key_base: e6638b4a158279048050953864dd75e1e54db60d6e992559636a8f7ca0bcf1b6e65caf39988117919d1b5d24d97732fe36d452940ca82169b46276227b3c8f0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
